name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install MoonBit
      run: |
        curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
        echo "$HOME/.moon/bin" >> $GITHUB_PATH
      
    - name: Check format
      run: moon fmt --check
      
    - name: Build
      run: moon build
      
    - name: Test
      run: moon test
      
    - name: Check
      run: moon check 