name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MoonBit
      uses: moonbitlang/setup-moonbit@v1
      
    - name: Check format
      run: moon fmt --check
      
    - name: Build
      run: moon build
      
    - name: Test
      run: moon test
      
    - name: Check
      run: moon check 